### ISSUE TITLE
Run inference.py and error is Operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by alex89607** [Attila94/refinenet-keras#7]
Think its my fault, but may be you give me any route?
My error is:

    tracking <tf.Variable 'scale5c_branch2b/scale5c_branch2b_beta:0' shape=(512,) dtype=float32> beta
    tracking <tf.Variable 'scale5c_branch2c/scale5c_branch2c_gamma:0' shape=(2048,) dtype=float32> gamma
    tracking <tf.Variable 'scale5c_branch2c/scale5c_branch2c_beta:0' shape=(2048,) dtype=float32> beta
    Traceback (most recent call last):
      File "D:\-inst\Python\Python373\lib\contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "D:\-inst\Python\Python373\lib\site-packages\tensorflow\python\framework\ops.py", line 5652, in get_controller
        yield g
      File "D:\-inst\Python\Python373\lib\site-packages\keras\engine\base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
      File "D:\-inst\Python\Python373\lib\site-packages\keras\layers\merge.py", line 91, in build
    shape)
      File "D:\-inst\Python\Python373\lib\site-packages\keras\layers\merge.py", line 61, in _compute_elemwise_op_output_shape
        str(shape1) + ' ' + str(shape2))
**ValueError: Operands could not be broadcast together with shapes (136, 240, 256) (135, 240, 256)**

**Comment by Attila94** [comment]
Try a different input size, looks like the size you're using causes some incompatibility between different feature maps somewhere in the network.
