### ISSUE TITLE
ValueError: Operands could not be broadcast together with shapes (18, 18, 256) (17, 17, 256)

### ISSUE THREAD

**Issue by katrin1401** [Attila94/refinenet-keras#9]
Hi,

Thank you for sharing your work.
Sorry to bother you, as I see no issues related to my error, I assume the error is mine.
After severals tries to fix it, I think I rather ask it.

The line: model = build_refinenet(input_shape, num_class, resnet_weights = frontend_weights, frontend_trainable = frontend_trainable)  gives me an error I am unavle to solve. 

The build refinenet function is able to read call and terurn the resnet101 model and prints: "Frontend weights loaded." After that it reads in all the high inputs, and low[0], but line 194 goes wrong. See full error log:

Traceback (most recent call last):
  File "C:/Users/KatrinKostova/refinenet-keras/train.py", line 80, in <module>
    model = build_refinenet(input_shape, num_class, resnet_weights = frontend_weights, frontend_trainable = frontend_trainable)
  File "C:\Users\KatrinKostova\refinenet-keras\model\refinenet.py", line 194, in build_refinenet
    low[1] = RefineBlock(high_inputs = high[1], low_inputs = low[0], block=3) # High input = ResNet 1/16, Low input = Previous 1/16
  File "C:\Users\KatrinKostova\refinenet-keras\model\refinenet.py", line 155, in RefineBlock
    name = 'rb_{}_mrf_'.format(block))
  File "C:\Users\KatrinKostova\refinenet-keras\model\refinenet.py", line 110, in MultiResolutionFusion
    return Add(name=name+'sum')([conv_low_up, conv_high])
  File "C:\Users\KatrinKostova\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "C:\Users\KatrinKostova\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\layers\merge.py", line 91, in build
    shape)
  File "C:\Users\KatrinKostova\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\layers\merge.py", line 61, in _compute_elemwise_op_output_shape
    str(shape1) + ' ' + str(shape2))
ValueError: Operands could not be broadcast together with shapes (18, 18, 256) (17, 17, 256)

Process finished with exit code 1

I dont know where 17 and 18 comes from. Did this problem occur to someone else too? Thank you in advance.

**Comment by Attila94** [comment]
Probably your input shape is not compatible with the model (downscaling and upscaling results in feature maps of different sizes due to round off errors, i.e. 18 and 17 in your case). Try a different input shapes where the width and height are even, e.g. 128 by 256.

**Comment by katrin1401** [comment]
Hi Attila, indeed the size 265, 265, 3 gave the error, but after seeing your answer and changing it to 384, 384, 3 it worked! Thanks for the super quick reply!
